col_remapper_train:
  aliases:
    output: output_col_remapper_train
  chunk_size: 100000
  columns:
    coadd_objects_id: id
    dec: coord_dec
    mag_g: mag_g_lsst
    mag_i: mag_r_lsst
    mag_r: mag_i_lsst
    mag_u: mag_u_lsst
    mag_y: mag_y_lsst
    mag_z: mag_z_lsst
    magerr_g: mag_err_g_lsst
    magerr_i: mag_err_r_lsst
    magerr_r: mag_err_i_lsst
    magerr_u: mag_err_u_lsst
    magerr_y: mag_err_y_lsst
    magerr_z: mag_err_z_lsst
    ra: coord_ra
    z_true: redshift
  config: null
  inplace: false
  input: None
  name: col_remapper_train
  output_mode: default
estimate_bpz:
  aliases:
    model: model_inform_bpzlite
    output: output_estimate_bpz
  band_err_names: &id001
  - mag_err_u_lsst
  - mag_err_g_lsst
  - mag_err_r_lsst
  - mag_err_i_lsst
  - mag_err_z_lsst
  - mag_err_y_lsst
  band_names: &id002
  - mag_u_lsst
  - mag_g_lsst
  - mag_r_lsst
  - mag_i_lsst
  - mag_z_lsst
  - mag_y_lsst
  chunk_size: 10000
  columns_file: /home/heloisamengisztki/WORK/ic-photoz/Fase2-RAIL/configs/bpz.columns
  config: null
  data_path: None
  dz: 0.01
  gauss_kernel: 0.0
  hdf5_groupname: ''
  input: None
  madau_flag: 'no'
  mag_err_min: 0.005
  mag_limits:
    mag_g_lsst: 29.04
    mag_i_lsst: 28.62
    mag_r_lsst: 29.06
    mag_u_lsst: 27.79
    mag_y_lsst: 27.05
    mag_z_lsst: 27.98
  model: inprogress_trained_BPZ_output.pkl
  name: estimate_bpz
  no_prior: true
  nondetect_val: 99.0
  nzbins: 301
  output_mode: default
  p_min: 0.005
  prior_band: mag_i_lsst
  spectra_file: SED/CWWSB4.list
  zmax: 3.0
  zmin: 0.0
  zp_errors:
  - 0.01
  - 0.01
  - 0.01
  - 0.01
  - 0.01
  - 0.01
inform_bpzlite:
  aliases:
    model: model_inform_bpzlite
  band_err_names: *id001
  band_names: *id002
  columns_file: /home/heloisamengisztki/WORK/ic-photoz/Fase2-RAIL/configs/bpz.columns
  config: null
  data_path: None
  hdf5_groupname: ''
  init_alpha: 1.8
  init_km: 0.1
  init_kt: 0.3
  init_zo: 0.4
  input: banana
  m0: 20.0
  mmax: 29.0
  mmin: 18.0
  model: trained_BPZ_output.pkl
  name: inform_bpzlite
  nondetect_val: 99.0
  nt_array:
  - 1
  - 2
  - 3
  nzbins: 301
  output_mode: default
  prior_band: mag_r_lsst
  redshift_col: redshift
  save_train: true
  spectra_file: SED/CWWSB4.list
  type_file: ''
  zmax: 3.0
  zmin: 0.0
